# This Template is for the publicly accessible demo deployment at cakeinc-vpc-app.projects.robertcurran.uk
# API: cakeinc-vpc-app-api.projects.robertcurran.uk
# Template Contains:
# * CloudFront Distribution
# * S3 Source Bucket
# * Route 53 Alias Record In robertcurran.uk Hosted Zone
# * API Gateway
# * Lambda and associated permissions and roles

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Mappings:
  prod:
    config:
      webAppDomainName: cakeinc-vpc-app.projects.robertcurran.uk
      cakeAPIDomainName: cakeinc-vpc-app-api.projects.robertcurran.uk
      staticAssettsBucketname: vpc-only-test-public-site-source

Resources:

  cakesAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowHeaders: "'Authorization, content-type'"
        AllowOrigin: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false # removes auth requirement from 'options' pre-flight requests
      Domain:
        DomainName: !FindInMap [prod, config, cakeAPIDomainName]
        CertificateArn: !ImportValue environmentStack--RobertCurranUkSSLCertificateEUWest1
        Route53:
          HostedZoneId: !ImportValue environmentStack--RobertCurranUKHostedZoneID

  getCakesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: build/cakes.handler
      Runtime: nodejs10.x
      CodeUri: .
      Description: >-
        A test function
      MemorySize: 128
      Timeout: 10
      ReservedConcurrentExecutions: 10
      Environment:
        Variables:
          NODE_ENV: prod
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref cakesAPI
            Path: /
            Method: Get

  staticSiteSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !FindInMap [prod, config, staticAssettsBucketname]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  staticSiteSourceBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref staticSiteSourceBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "staticSiteSourceBucket"
                  - "/*"
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity "
                    - Ref: staticSiteSourceBucketOriginAccessIdentity
                    - ""

  staticSiteSourceBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'staticSiteSourceBucket Origin Access Identity For CloudFront Distribution'

  cakeAppWebDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !FindInMap [prod, config, webAppDomainName]
        Origins:
          - DomainName: !GetAtt [staticSiteSourceBucket, RegionalDomainName]
            Id: 'staticSiteSourceBucketOrigin'
            S3OriginConfig:
              OriginAccessIdentity:
                "Fn::Join": [ "", ["origin-access-identity/cloudfront/",
                                   { "Ref": "staticSiteSourceBucketOriginAccessIdentity" }]]
        Enabled: true
        IPV6Enabled: true
        Comment: "cake app public deployment of web distribution"
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: 'false'
          Bucket: 'logs.static.robertcurran.s3.amazonaws.com'
          Prefix: 'vpc-cloudfront-test/publicDeployment/CloudFront/'
        DefaultCacheBehavior:
          TargetOriginId: 'staticSiteSourceBucketOrigin'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: 'false'
          ViewerProtocolPolicy: 'redirect-to-https'
        # CloudFront price classes described at: http://aws.amazon.com/cloudfront/pricing/
        # At time of writing Price Class 100 is EU and North America
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !ImportValue environmentStack--RobertCurranUKSSLCertificateUSEast1
          MinimumProtocolVersion: 'TLSv1.2_2018'
          SslSupportMethod: 'sni-only'
