# WARNING, as Stack Exports are scoped to the region and this is in the global us-east-1 region where
# the rest of the resources are in eu-west-1 I have just manually linked in the ARN for the
# vpcCloudFrontTestFireWall in the cloudfront distribution in the main template,
# this will need manual sorting to deploy...


AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  vpcNATGatewayEIP:
    Type: "String"
    Description: Elastic IP of the NAT Gateway Attached to the target VPC

Resources:

  # WAF FIREWALLS With Scope of CloudFront Must Be Deployed to US-1!
  vpcNATGatewayBlockIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses:
        - !Ref vpcNATGatewayEIP
      Description: 'VPC Nat Gateway EIP'
      IPAddressVersion: 'IPV4'
      Name: 'vpNatGateWayEIPSet'
      Scope: 'CLOUDFRONT'

  vpcCloudFrontTestFireWall:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Block: {}
      Description: 'vpcCloudFrontTest WebACL'
      Name: 'vpcCloudFrontTestFireWall'
      Rules:
        - Action:
            Allow: {}
          Name: 'allowRequestsFromWithinVPC'
          Priority: 0
          Statement:
            IPSetReferenceStatement:
              ARN:
                Fn::GetAtt:
                  - vpcNATGatewayBlockIPSet
                  - Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: 'true'
            MetricName: 'vpcCloudFrontTest-WAF-VPCOriginOnly'
            SampledRequestsEnabled: 'true'
      Scope: 'CLOUDFRONT'
      VisibilityConfig:
        CloudWatchMetricsEnabled: 'true'
        MetricName: 'vpcCloudFrontTest-WAF'
        SampledRequestsEnabled: 'true'


